name: .NET Core Desktop

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2019

    env:
      Solution_Name: ForsHops.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore and Build the application
      run: |
        msbuild ${{ github.workspace }}/ForsHops.sln /t:Restore,Build /p:Configuration=${{ matrix.configuration }}
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Verify Build Output
      run: dir "${{ github.workspace }}/ForsHops/bin/Release"

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: ForsHops
        path: ${{ github.workspace }}/ForsHops/bin/Release/**
